services:
  prefect-server:
    image: prefecthq/prefect:2.20-python3.12
    ports:
      - "4200:4200"
    networks:
      - prefect-network
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:admin@postgres:5432/prefect
    healthcheck:
      test: echo "ready"
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    depends_on:
      postgres:
        condition: service_healthy
    command: ["prefect", "server", "start", "--host", "0.0.0.0"]

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - prefect-network
    volumes:
      - type: bind
        source: ./db/mongo_data
        target: /data/db

  prefect-agent:
    image: sunbeam-prefect-agent:latest
    volumes:
      - ./fs_data:/app/fs_data
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: .
      dockerfile: ./Dockerfile

    depends_on:
      prefect-server:
        condition: service_healthy
    networks:
      - prefect-network
    environment:
      - PREFECT_API_URL=http://172.17.0.1:4200/api
      - PREFECT_API_DATABASE_CONNECTION_URL="postgresql+asyncpg://prefect:yourpassword@postgres:5432/prefect"
#    env_file: "./pipeline/.env"
    # Note: the last command blocks (so insert any additonal commands before the last one!)
    command: > 
      sh -c "ln -s config/.env . && 
             export $(cat .env | xargs) && 
             uv run prefect work-pool create --type docker docker-work-pool --overwrite &&
             uv run prefect worker start --pool docker-work-pool"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: prefect
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    restart: always
    networks:
      - prefect-network
    volumes:
      - type: bind
        source: ./db/pg_data
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect -d prefect"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  external_api:
    image: sunbeam-external-api:latest
    build:
      context: .
      dockerfile: external.Dockerfile

    networks:
      - prefect-network
    ports:
      - "8080:8080"
    environment:
      - PREFECT_API_URL=http://172.17.0.1:4200/api
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:yourpassword@postgres:5432/prefect

    depends_on:
      prefect-server:
        condition: service_healthy

    command: >
      sh -c "uv run python external/external.py" 

networks:
  prefect-network:
    driver: bridge
