services:
  db:
    networks:
      - sunbeam-net
    image: timescale/timescaledb:2.14.2-pg16
    container_name: sunbeam-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: telemetry
      POSTGRES_PASSWORD: telemetry
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U telemetry -d telemetry"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    networks:
      - sunbeam-net
    container_name: sunbeam-server
    environment:
      PYTHONUNBUFFERED: "1"
    depends_on:
      - db
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  dashboard:
    networks:
      - sunbeam-net
    container_name: sunbeam-dashboard
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    depends_on:
      - server

volumes:
  telemetry_db_data:

networks:
  sunbeam-net:
    name: sunbeam-net