"""worker kind for self-registered workers

Revision ID: 6044f7bdb7d9
Revises: f3f709edb0e7
Create Date: 2026-07-19 16:40:01.462001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6044f7bdb7d9'
down_revision: Union[str, Sequence[str], None] = 'f3f709edb0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


workerkind = sa.Enum('CONTAINER', 'EXTERNAL', name='workerkind')

# Note: autogenerate also proposed dropping the aligned_sample/raw_sample
# indexes because they live in the baseline's raw SQL (and Timescale's
# automatic ts indexes), not in the model metadata. Those drops were removed
# by hand - do the same if future autogenerated drafts propose them again.


def upgrade() -> None:
    """Upgrade schema."""
    # ADD COLUMN does not create the enum type implicitly on Postgres.
    workerkind.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'worker_run',
        sa.Column('kind', workerkind, server_default='CONTAINER', nullable=False),
    )
    op.alter_column('worker_run', 'image_tag',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column('worker_run', 'image_tag',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('worker_run', 'kind')

    workerkind.drop(op.get_bind(), checkfirst=True)
