"""baseline schema

Revision ID: f3f709edb0e7
Revises: 
Create Date: 2026-07-19 15:35:36.186136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f709edb0e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vehicle_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pipeline_edition', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('UNPROCESSED', 'ONGOING', 'PROCESSED', name='eventstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('signal',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'name', name='uq_signal_event_name')
    )
    op.create_table('worker_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('pipeline_edition', sa.String(length=32), nullable=False),
    sa.Column('image_tag', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'STARTING', 'RUNNING', 'STOP_REQUESTED', 'STOPPING', 'COMPLETED', 'FAILED', 'LOST', 'CANCELLED', name='workerstatus'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('container_id', sa.String(length=255), nullable=True),
    sa.Column('container_name', sa.String(length=255), nullable=True),
    sa.Column('current_stage', sa.String(length=255), nullable=True),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('stop_requested', sa.Boolean(), nullable=False),
    sa.Column('stop_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aligned_sample',
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('value_f64', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signal.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'signal_id', 'ts', name='pk_aligned_sample')
    )
    op.create_table('raw_sample',
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('value_f64', sa.Float(), nullable=False),
    sa.Column('ingest_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_message_type', sa.String(length=255), nullable=True),
    sa.Column('source_sequence', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signal.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'signal_id', 'ts', name='pk_raw_sample')
    )
    # ### end Alembic commands ###

    # TimescaleDB hypertables + query indexes (mirrors db/sunbeamdb/init_db.py).
    op.execute(
        """
        SELECT create_hypertable(
            'raw_sample',
            'ts',
            chunk_time_interval => INTERVAL '1 day',
            if_not_exists => TRUE
        );
        """
    )
    op.execute(
        """
        SELECT create_hypertable(
            'aligned_sample',
            'ts',
            chunk_time_interval => INTERVAL '1 day',
            if_not_exists => TRUE
        );
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS aligned_sample_event_signal_ts_idx
        ON aligned_sample (event_id, signal_id, ts DESC);
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS aligned_sample_event_ts_idx
        ON aligned_sample (event_id, ts DESC);
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_sample')
    op.drop_table('aligned_sample')
    op.drop_table('worker_run')
    op.drop_table('signal')
    op.drop_table('event')
    op.drop_table('vehicle')
    # ### end Alembic commands ###

    op.execute("DROP TYPE IF EXISTS workerstatus;")
    op.execute("DROP TYPE IF EXISTS eventstatus;")
