[[event]]
name = "FSGP_2024_Day_1"
vehicle = "Brightside"
description = "First day of FSGP 2024 at NCM Motorsports"
stages = ["Power", "Efficiency"]
starts_at = "2024-07-16T04:00:00Z"
ends_at = "2024-07-17T04:00:00Z"
pipeline_edition = "v3_0"

[[event]]
name = "realtime"
vehicle = "Brightside"
description = "Ongoing"
stages = ["Array", "MotorPower", "PackPower", "IntegratedPackPower", "Efficiency"]
starts_at = "2026-05-30T01:00:00Z"
pipeline_edition = "v3_0"
