[[target]]
name = "GPSFix"
field = "GPSFix"
type = "TimeSeries"
measurement = "TEL"
car = "Brightside"
bucket = "CAN_test"
frequency = 1.0
units = "V"
description = "Voltage of array string 2"

[[target]]
name = "TotalPackVoltage"
field = "TotalPackVoltage"
type = "TimeSeries"
measurement = "BMS"
frequency = 1.0
units = "V"
car = "Brightside"
bucket = "CAN_test"
description = "Voltage of the battery"