[[target]]
name = "TotalPackVoltage"
field = "TotalPackVoltage"
type = "TimeSeries"
measurement = "BMS"
frequency = 1.0
units = "V"
car = "Brightside"
bucket = "CAN_log"
description = "Voltage of the battery"

[[target]]
name = "PackCurrent"
field = "PackCurrent"
type = "TimeSeries"
measurement = "ECU"
car = "Brightside"
bucket = "CAN_log"
frequency = 10.0
units = "A"
description = "The signed current flowing out of the battery (+ means drawing energy, - means storing energy)"
