[config]
events_description_file = "events.toml"
ingress_description_file = "ingress.toml"
stages_to_run = [
    "energy"
]

[stage_data_source]
data_source_type = "MongoDBDataSource"

[stage_data_source.FSDataSource]
fs_root = "fs_data"

[stage_data_source.MongoDBDataSource]

[stage_data_source.InfluxDBDataSource]

[ingress_data_source]
data_source_type = "MongoDBDataSource"

[ingress_data_source.MongoDBDataSource]
ingress_origin = "influxdb_cache"

[ingress_data_source.SunbeamDataSource]
api_url = "api.sunbeam.ubcsolar.com"

[ingress_data_source.FSDataSource]
fs_root = "fs_data"

[ingress_data_source.InfluxDBDataSource]
start = "2024-07-01T01:00:00Z"
stop = "2024-08-30T01:00:00Z"
