[config]
start = "2024-07-01T01:00:00Z"
stop = "2024-08-30T01:00:00Z"

[[target]]
name = "TotalPackVoltage"
field = "TotalPackVoltage"
type = "TimeSeries"
measurement = "BMS"
frequency = 1.0
units = "V"
car = "Brightside"
bucket = "CAN_log"

[[target]]
name = "PackCurrent"
field = "PackCurrent"
type = "TimeSeries"
measurement = "ECU"
car = "Brightside"
bucket = "CAN_log"
frequency = 10.0
units = "A"
