[config]
start = "2024-07-01T01:00:00Z"
stop = "2024-08-30T01:00:00Z"
data_source = "FSDataSource"
root = "fs_data"

[[target]]
name = "TotalPackVoltage"
field = "TotalPackVoltage"
type = "TimeSeries"
measurement = "BMS"
frequency = 1.0
units = "V"
car = "Brightside"
bucket = "CAN_log"

[[target]]
name = "PackCurrent"
field = "PackCurrent"
type = "TimeSeries"
measurement = "ECU"
car = "Brightside"
bucket = "CAN_log"
frequency = 10.0
units = "A"

[[target]]
name = "MechBrakePressed"
field = "MechBrakePressed"
type = "TimeSeries"
measurement = "MCB"
car = "Brightside"
bucket = "CAN_log"
frequency = 10.0
units = "A.U."

[[target]]
name = "VehicleVelocity"
field = "VehicleVelocity"
type = "TimeSeries"
measurement = "MDI"
car = "Brightside"
bucket = "CAN_log"
frequency = 5.0
units = "m/s"

[[target]]
name = "AcceleratorPosition"
field = "AcceleratorPosition"
type = "TimeSeries"
measurement = "MC"
car = "Brightside"
bucket = "CAN_log"
frequency = 5.0
units = "A.U."

[[target]]
name = "BatteryCurrent"
field = "BatteryCurrent"
type = "TimeSeries"
measurement = "MC"
car = "Brightside"
bucket = "CAN_log"
frequency = 5.0
units = "A"

[[target]]
name = "BatteryVoltage"
field = "BatteryVoltage"
type = "TimeSeries"
measurement = "MC"
car = "Brightside"
bucket = "CAN_log"
frequency = 5.0
units = "A"
