[config]
events_description_file = "config/events.toml"
stage_data_source = "MongoDBDataSource"
stage_data_source_description_file = "config/FSDataSource.toml"
ingress_description_file = "config/ingress.toml"
ingress_data_source_description_file = "config/ingress_data_source.toml"