[v3_0]
name = "Brightside 2024"

[v3_0.Ingress]
module = "stage.v3_0.ingress"
class = "Ingress"

[v3_0.Efficiency]
module = "stage.v3_0.efficiency"
class = "Efficiency"

[v3_0.MotorSpeed]
module = "stage.v3_0.motor_speed"
class = "MotorSpeed"

[v3_0.Array]
module = "stage.v3_0.array"
class = "Array"

[v3_0.MotorPower]
module = "stage.v3_0.motor_power"
class = "MotorPower"

[v3_0.PackPower]
module = "stage.v3_0.pack_power"
class = "PackPower"