from datetime import timezone, datetime
from typing import Protocol

class TimeProvider(Protocol):
    def now(self, tz: timezone) -> datetime: ...

class IngressObserver(Protocol):
    """ Receives progress events from ingress queries. Implementations decide how (or whether) to display them. """
    def on_query_start(self, field: str) -> None: ...
    def on_query_done(self, field: str, points: int, elapsed_s: float) -> None: ...
    def on_query_failed(self, field: str, error: BaseException) -> None: ...
