[config]
start = "2024-07-01T01:00:00Z"
end = "2024-08-30T01:00:00Z"

[[target]]
field = "TotalPackVoltage"
measurement = "BMS"
frequency = 5.0
units = "V"

[[target]]
field = "VehicleVelocity"
measurement = "MDI"
frequency = 1.0
units = "m/s"